//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Game {
    
    private CT_Identity identityField;
    
    private CT_ShellVisuals shellVisualsField;
    
    private CT_ResourcesResource[] resourcesField;
    
    private CT_ExecutableList executableListField;
    
    private string gameOsVersionField;
    
    private CT_MediaCapture mediaCaptureField;
    
    private string storeIdField;
    
    private CT_AllowedProductsList allowedProductsField;
    
    private CT_RelatedProductsList relatedProductsField;
    
    private CT_PersistentLocalStorage persistentLocalStorageField;
    
    private CT_VirtualMachine virtualMachineField;
    
    private bool mSAFullTrustField;
    
    private bool mSAFullTrustFieldSpecified;
    
    private string mSAAppIdField;
    
    private string titleIdField;
    
    private bool requiresXboxLiveField;
    
    private bool requiresXboxLiveFieldSpecified;
    
    private CT_ExtendedAttributeList extendedAttributeListField;
    
    private CT_DesktopRegistration desktopRegistrationField;
    
    private CT_DevelopmentOnly developmentOnlyField;
    
    private string configVersionField;
    
    /// <remarks/>
    public CT_Identity Identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
    
    /// <remarks/>
    public CT_ShellVisuals ShellVisuals {
        get {
            return this.shellVisualsField;
        }
        set {
            this.shellVisualsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
    public CT_ResourcesResource[] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    public CT_ExecutableList ExecutableList {
        get {
            return this.executableListField;
        }
        set {
            this.executableListField = value;
        }
    }
    
    /// <remarks/>
    public string GameOsVersion {
        get {
            return this.gameOsVersionField;
        }
        set {
            this.gameOsVersionField = value;
        }
    }
    
    /// <remarks/>
    public CT_MediaCapture MediaCapture {
        get {
            return this.mediaCaptureField;
        }
        set {
            this.mediaCaptureField = value;
        }
    }
    
    /// <remarks/>
    public string StoreId {
        get {
            return this.storeIdField;
        }
        set {
            this.storeIdField = value;
        }
    }
    
    /// <remarks/>
    public CT_AllowedProductsList AllowedProducts {
        get {
            return this.allowedProductsField;
        }
        set {
            this.allowedProductsField = value;
        }
    }
    
    /// <remarks/>
    public CT_RelatedProductsList RelatedProducts {
        get {
            return this.relatedProductsField;
        }
        set {
            this.relatedProductsField = value;
        }
    }
    
    /// <remarks/>
    public CT_PersistentLocalStorage PersistentLocalStorage {
        get {
            return this.persistentLocalStorageField;
        }
        set {
            this.persistentLocalStorageField = value;
        }
    }
    
    /// <remarks/>
    public CT_VirtualMachine VirtualMachine {
        get {
            return this.virtualMachineField;
        }
        set {
            this.virtualMachineField = value;
        }
    }
    
    /// <remarks/>
    public bool MSAFullTrust {
        get {
            return this.mSAFullTrustField;
        }
        set {
            this.mSAFullTrustField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MSAFullTrustSpecified {
        get {
            return this.mSAFullTrustFieldSpecified;
        }
        set {
            this.mSAFullTrustFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string MSAAppId {
        get {
            return this.mSAAppIdField;
        }
        set {
            this.mSAAppIdField = value;
        }
    }
    
    /// <remarks/>
    public string TitleId {
        get {
            return this.titleIdField;
        }
        set {
            this.titleIdField = value;
        }
    }
    
    /// <remarks/>
    public bool RequiresXboxLive {
        get {
            return this.requiresXboxLiveField;
        }
        set {
            this.requiresXboxLiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresXboxLiveSpecified {
        get {
            return this.requiresXboxLiveFieldSpecified;
        }
        set {
            this.requiresXboxLiveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CT_ExtendedAttributeList ExtendedAttributeList {
        get {
            return this.extendedAttributeListField;
        }
        set {
            this.extendedAttributeListField = value;
        }
    }
    
    /// <remarks/>
    public CT_DesktopRegistration DesktopRegistration {
        get {
            return this.desktopRegistrationField;
        }
        set {
            this.desktopRegistrationField = value;
        }
    }
    
    /// <remarks/>
    public CT_DevelopmentOnly DevelopmentOnly {
        get {
            return this.developmentOnlyField;
        }
        set {
            this.developmentOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string configVersion {
        get {
            return this.configVersionField;
        }
        set {
            this.configVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_Identity {
    
    private string nameField;
    
    private string publisherField;
    
    private string resourceIdField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_DebugNetworkPortList {
    
    private string[] debugNetworkPortField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DebugNetworkPort")]
    public string[] DebugNetworkPort {
        get {
            return this.debugNetworkPortField;
        }
        set {
            this.debugNetworkPortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_DevelopmentOnly {
    
    private string contentIdOverrideField;
    
    private string eKBIDOverrideField;
    
    private CT_DebugNetworkPortList debugNetworkPortListField;
    
    /// <remarks/>
    public string ContentIdOverride {
        get {
            return this.contentIdOverrideField;
        }
        set {
            this.contentIdOverrideField = value;
        }
    }
    
    /// <remarks/>
    public string EKBIDOverride {
        get {
            return this.eKBIDOverrideField;
        }
        set {
            this.eKBIDOverrideField = value;
        }
    }
    
    /// <remarks/>
    public CT_DebugNetworkPortList DebugNetworkPortList {
        get {
            return this.debugNetworkPortListField;
        }
        set {
            this.debugNetworkPortListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_FileTypeAssociation {
    
    private string displayNameField;
    
    private string logoField;
    
    private string infoTipField;
    
    private CT_FileTypeAssociationEditFlags editFlagsField;
    
    private CT_FTASupportedFileTypesFileType[] supportedFileTypesField;
    
    private string nameField;
    
    private string executableField;
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string Logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    public string InfoTip {
        get {
            return this.infoTipField;
        }
        set {
            this.infoTipField = value;
        }
    }
    
    /// <remarks/>
    public CT_FileTypeAssociationEditFlags EditFlags {
        get {
            return this.editFlagsField;
        }
        set {
            this.editFlagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("FileType", IsNullable=false)]
    public CT_FTASupportedFileTypesFileType[] SupportedFileTypes {
        get {
            return this.supportedFileTypesField;
        }
        set {
            this.supportedFileTypesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Executable {
        get {
            return this.executableField;
        }
        set {
            this.executableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_FileTypeAssociationEditFlags {
    
    private bool openIsSafeField;
    
    private bool openIsSafeFieldSpecified;
    
    private bool alwaysUnsafeField;
    
    private bool alwaysUnsafeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool OpenIsSafe {
        get {
            return this.openIsSafeField;
        }
        set {
            this.openIsSafeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpenIsSafeSpecified {
        get {
            return this.openIsSafeFieldSpecified;
        }
        set {
            this.openIsSafeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AlwaysUnsafe {
        get {
            return this.alwaysUnsafeField;
        }
        set {
            this.alwaysUnsafeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AlwaysUnsafeSpecified {
        get {
            return this.alwaysUnsafeFieldSpecified;
        }
        set {
            this.alwaysUnsafeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_FTASupportedFileTypesFileType {
    
    private string contentTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ContentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_UninstallActionList {
    
    private CT_CustomInstallAction[] uninstallActionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UninstallAction")]
    public CT_CustomInstallAction[] UninstallAction {
        get {
            return this.uninstallActionField;
        }
        set {
            this.uninstallActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_CustomInstallAction {
    
    private string fileField;
    
    private string nameField;
    
    private string argumentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Arguments {
        get {
            return this.argumentsField;
        }
        set {
            this.argumentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_RepairActionList {
    
    private CT_CustomInstallAction[] repairActionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RepairAction")]
    public CT_CustomInstallAction[] RepairAction {
        get {
            return this.repairActionField;
        }
        set {
            this.repairActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_InstallActionList {
    
    private CT_CustomInstallAction[] installActionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InstallAction")]
    public CT_CustomInstallAction[] InstallAction {
        get {
            return this.installActionField;
        }
        set {
            this.installActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_CustomInstallActions {
    
    private string folderField;
    
    private CT_InstallActionList installActionListField;
    
    private CT_RepairActionList repairActionListField;
    
    private CT_UninstallActionList uninstallActionListField;
    
    /// <remarks/>
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    public CT_InstallActionList InstallActionList {
        get {
            return this.installActionListField;
        }
        set {
            this.installActionListField = value;
        }
    }
    
    /// <remarks/>
    public CT_RepairActionList RepairActionList {
        get {
            return this.repairActionListField;
        }
        set {
            this.repairActionListField = value;
        }
    }
    
    /// <remarks/>
    public CT_UninstallActionList UninstallActionList {
        get {
            return this.uninstallActionListField;
        }
        set {
            this.uninstallActionListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_DependencyList {
    
    private CT_DependencyListKnownDependency[] knownDependencyField;
    
    private CT_DependencyListDependency[] dependencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KnownDependency")]
    public CT_DependencyListKnownDependency[] KnownDependency {
        get {
            return this.knownDependencyField;
        }
        set {
            this.knownDependencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dependency")]
    public CT_DependencyListDependency[] Dependency {
        get {
            return this.dependencyField;
        }
        set {
            this.dependencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_DependencyListKnownDependency {
    
    private ST_KnownDependency nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ST_KnownDependency Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum ST_KnownDependency {
    
    /// <remarks/>
    DX11,
    
    /// <remarks/>
    VC11,
    
    /// <remarks/>
    VC12,
    
    /// <remarks/>
    VC14,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_DependencyListDependency {
    
    private string nameField;
    
    private string minVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinVersion {
        get {
            return this.minVersionField;
        }
        set {
            this.minVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_DesktopRegistration {
    
    private ST_ProcessorArchitecture processorArchitectureField;
    
    private bool processorArchitectureFieldSpecified;
    
    private CT_DesktopRegistrationMainPackageDependency mainPackageDependencyField;
    
    private CT_DependencyList dependencyListField;
    
    private CT_CustomInstallActions customInstallActionsField;
    
    private CT_DesktopRegistrationModFolder modFolderField;
    
    private bool disableRegistryWriteVirtualizationField;
    
    private bool disableRegistryWriteVirtualizationFieldSpecified;
    
    private bool disableFilesystemWriteVirtualizationField;
    
    private bool disableFilesystemWriteVirtualizationFieldSpecified;
    
    private CT_DesktopRegistrationMultiplayerProtocol multiplayerProtocolField;
    
    private CT_FileTypeAssociation fileTypeAssociationField;
    
    /// <remarks/>
    public ST_ProcessorArchitecture ProcessorArchitecture {
        get {
            return this.processorArchitectureField;
        }
        set {
            this.processorArchitectureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProcessorArchitectureSpecified {
        get {
            return this.processorArchitectureFieldSpecified;
        }
        set {
            this.processorArchitectureFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CT_DesktopRegistrationMainPackageDependency MainPackageDependency {
        get {
            return this.mainPackageDependencyField;
        }
        set {
            this.mainPackageDependencyField = value;
        }
    }
    
    /// <remarks/>
    public CT_DependencyList DependencyList {
        get {
            return this.dependencyListField;
        }
        set {
            this.dependencyListField = value;
        }
    }
    
    /// <remarks/>
    public CT_CustomInstallActions CustomInstallActions {
        get {
            return this.customInstallActionsField;
        }
        set {
            this.customInstallActionsField = value;
        }
    }
    
    /// <remarks/>
    public CT_DesktopRegistrationModFolder ModFolder {
        get {
            return this.modFolderField;
        }
        set {
            this.modFolderField = value;
        }
    }
    
    /// <remarks/>
    public bool DisableRegistryWriteVirtualization {
        get {
            return this.disableRegistryWriteVirtualizationField;
        }
        set {
            this.disableRegistryWriteVirtualizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisableRegistryWriteVirtualizationSpecified {
        get {
            return this.disableRegistryWriteVirtualizationFieldSpecified;
        }
        set {
            this.disableRegistryWriteVirtualizationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool DisableFilesystemWriteVirtualization {
        get {
            return this.disableFilesystemWriteVirtualizationField;
        }
        set {
            this.disableFilesystemWriteVirtualizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisableFilesystemWriteVirtualizationSpecified {
        get {
            return this.disableFilesystemWriteVirtualizationFieldSpecified;
        }
        set {
            this.disableFilesystemWriteVirtualizationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CT_DesktopRegistrationMultiplayerProtocol MultiplayerProtocol {
        get {
            return this.multiplayerProtocolField;
        }
        set {
            this.multiplayerProtocolField = value;
        }
    }
    
    /// <remarks/>
    public CT_FileTypeAssociation FileTypeAssociation {
        get {
            return this.fileTypeAssociationField;
        }
        set {
            this.fileTypeAssociationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum ST_ProcessorArchitecture {
    
    /// <remarks/>
    x64,
    
    /// <remarks/>
    x86,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_DesktopRegistrationMainPackageDependency {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_DesktopRegistrationModFolder {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_DesktopRegistrationMultiplayerProtocol {
    
    private string executableField;
    
    private bool valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Executable {
        get {
            return this.executableField;
        }
        set {
            this.executableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_ExtendedAttributeList {
    
    private CT_ExtendedAttributeListExtendedAttribute[] extendedAttributeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtendedAttribute")]
    public CT_ExtendedAttributeListExtendedAttribute[] ExtendedAttribute {
        get {
            return this.extendedAttributeField;
        }
        set {
            this.extendedAttributeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_ExtendedAttributeListExtendedAttribute {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_VirtualMachine {
    
    private ST_MemoryConfig xboxOneXTitleMemoryField;
    
    private bool xboxOneXTitleMemoryFieldSpecified;
    
    private ST_MemoryConfig xboxAnacondaTitleMemoryField;
    
    private bool xboxAnacondaTitleMemoryFieldSpecified;
    
    private bool sMTEnabledField;
    
    private bool sMTEnabledFieldSpecified;
    
    private bool requiresEraShimField;
    
    private bool requiresEraShimFieldSpecified;
    
    /// <remarks/>
    public ST_MemoryConfig XboxOneXTitleMemory {
        get {
            return this.xboxOneXTitleMemoryField;
        }
        set {
            this.xboxOneXTitleMemoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XboxOneXTitleMemorySpecified {
        get {
            return this.xboxOneXTitleMemoryFieldSpecified;
        }
        set {
            this.xboxOneXTitleMemoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ST_MemoryConfig XboxAnacondaTitleMemory {
        get {
            return this.xboxAnacondaTitleMemoryField;
        }
        set {
            this.xboxAnacondaTitleMemoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XboxAnacondaTitleMemorySpecified {
        get {
            return this.xboxAnacondaTitleMemoryFieldSpecified;
        }
        set {
            this.xboxAnacondaTitleMemoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool SMTEnabled {
        get {
            return this.sMTEnabledField;
        }
        set {
            this.sMTEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SMTEnabledSpecified {
        get {
            return this.sMTEnabledFieldSpecified;
        }
        set {
            this.sMTEnabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool RequiresEraShim {
        get {
            return this.requiresEraShimField;
        }
        set {
            this.requiresEraShimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresEraShimSpecified {
        get {
            return this.requiresEraShimFieldSpecified;
        }
        set {
            this.requiresEraShimFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum ST_MemoryConfig {
    
    /// <remarks/>
    Standard,
    
    /// <remarks/>
    Advanced,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_PersistentLocalStorage {
    
    private string sizeMBField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SizeMB {
        get {
            return this.sizeMBField;
        }
        set {
            this.sizeMBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_RelatedProductsList {
    
    private string[] relatedProductField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelatedProduct")]
    public string[] RelatedProduct {
        get {
            return this.relatedProductField;
        }
        set {
            this.relatedProductField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_AllowedProductsList {
    
    private string[] allowedProductField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowedProduct")]
    public string[] AllowedProduct {
        get {
            return this.allowedProductField;
        }
        set {
            this.allowedProductField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_MediaCapture {
    
    private bool gameDVRSystemComponentField;
    
    private bool gameDVRSystemComponentFieldSpecified;
    
    private bool blockBroadcastField;
    
    private bool blockBroadcastFieldSpecified;
    
    private bool blockGameDVRField;
    
    private bool blockGameDVRFieldSpecified;
    
    /// <remarks/>
    public bool GameDVRSystemComponent {
        get {
            return this.gameDVRSystemComponentField;
        }
        set {
            this.gameDVRSystemComponentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GameDVRSystemComponentSpecified {
        get {
            return this.gameDVRSystemComponentFieldSpecified;
        }
        set {
            this.gameDVRSystemComponentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool BlockBroadcast {
        get {
            return this.blockBroadcastField;
        }
        set {
            this.blockBroadcastField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BlockBroadcastSpecified {
        get {
            return this.blockBroadcastFieldSpecified;
        }
        set {
            this.blockBroadcastFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool BlockGameDVR {
        get {
            return this.blockGameDVRField;
        }
        set {
            this.blockGameDVRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BlockGameDVRSpecified {
        get {
            return this.blockGameDVRFieldSpecified;
        }
        set {
            this.blockGameDVRFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_ExecutableList {
    
    private CT_ExecutableListExecutable[] executableField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Executable")]
    public CT_ExecutableListExecutable[] Executable {
        get {
            return this.executableField;
        }
        set {
            this.executableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_ExecutableListExecutable {
    
    private string nameField;
    
    private ST_DeviceFamily targetDeviceFamilyField;
    
    private bool targetDeviceFamilyFieldSpecified;
    
    private string idField;
    
    private bool isDevOnlyField;
    
    private bool isDevOnlyFieldSpecified;
    
    private string overrideDisplayNameField;
    
    private string overrideLogoField;
    
    private string overrideSquare480x480LogoField;
    
    private string overrideSquare44x44LogoField;
    
    private string overrideSplashScreenImageField;
    
    private string aliasField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ST_DeviceFamily TargetDeviceFamily {
        get {
            return this.targetDeviceFamilyField;
        }
        set {
            this.targetDeviceFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TargetDeviceFamilySpecified {
        get {
            return this.targetDeviceFamilyFieldSpecified;
        }
        set {
            this.targetDeviceFamilyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsDevOnly {
        get {
            return this.isDevOnlyField;
        }
        set {
            this.isDevOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDevOnlySpecified {
        get {
            return this.isDevOnlyFieldSpecified;
        }
        set {
            this.isDevOnlyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OverrideDisplayName {
        get {
            return this.overrideDisplayNameField;
        }
        set {
            this.overrideDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OverrideLogo {
        get {
            return this.overrideLogoField;
        }
        set {
            this.overrideLogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OverrideSquare480x480Logo {
        get {
            return this.overrideSquare480x480LogoField;
        }
        set {
            this.overrideSquare480x480LogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OverrideSquare44x44Logo {
        get {
            return this.overrideSquare44x44LogoField;
        }
        set {
            this.overrideSquare44x44LogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OverrideSplashScreenImage {
        get {
            return this.overrideSplashScreenImageField;
        }
        set {
            this.overrideSplashScreenImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum ST_DeviceFamily {
    
    /// <remarks/>
    XboxOne,
    
    /// <remarks/>
    Scarlett,
    
    /// <remarks/>
    PC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CT_ShellVisuals {
    
    private string defaultDisplayNameField;
    
    private string publisherDisplayNameField;
    
    private string storeLogoField;
    
    private string square150x150LogoField;
    
    private string square44x44LogoField;
    
    private string square480x480LogoField;
    
    private string descriptionField;
    
    private ST_ForegroundText foregroundTextField;
    
    private bool foregroundTextFieldSpecified;
    
    private string backgroundColorField;
    
    private string splashScreenImageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefaultDisplayName {
        get {
            return this.defaultDisplayNameField;
        }
        set {
            this.defaultDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PublisherDisplayName {
        get {
            return this.publisherDisplayNameField;
        }
        set {
            this.publisherDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreLogo {
        get {
            return this.storeLogoField;
        }
        set {
            this.storeLogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Square150x150Logo {
        get {
            return this.square150x150LogoField;
        }
        set {
            this.square150x150LogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Square44x44Logo {
        get {
            return this.square44x44LogoField;
        }
        set {
            this.square44x44LogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Square480x480Logo {
        get {
            return this.square480x480LogoField;
        }
        set {
            this.square480x480LogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ST_ForegroundText ForegroundText {
        get {
            return this.foregroundTextField;
        }
        set {
            this.foregroundTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ForegroundTextSpecified {
        get {
            return this.foregroundTextFieldSpecified;
        }
        set {
            this.foregroundTextFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BackgroundColor {
        get {
            return this.backgroundColorField;
        }
        set {
            this.backgroundColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SplashScreenImage {
        get {
            return this.splashScreenImageField;
        }
        set {
            this.splashScreenImageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum ST_ForegroundText {
    
    /// <remarks/>
    light,
    
    /// <remarks/>
    dark,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CT_ResourcesResource {
    
    private string languageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}
