using System;
using XGamingRuntime.Interop;

namespace XGamingRuntime
{
    //enum class XblPrivacySetting : uint32_t
    //{
    //    Unknown = 0,
    //    ShareFriendList = 1,
    //    ShareGameHistory = 2,
    //    CommunicateUsingTextAndVoice = 3,
    //    SharePresence = 4,
    //    ShareProfile = 5,
    //    ShareVideoAndMusicStatus = 6,
    //    CommunicateUsingVideo = 7,
    //    CollectVoiceData = 8,
    //    ShareXboxMusicActivity = 9,
    //    ShareExerciseInfo = 11,
    //    ShareIdentity = 12,
    //    ShareIdentityInGame = 13,
    //    ShareRecordedGameSessions = 14,
    //    CollectLiveTvData = 15,
    //    CollectXboxVideoData = 16,
    //    ShareIdentityTransitively = 17,
    //    ShareVideoHistory = 18,
    //    ShareMusicHistory = 19,
    //    AllowUserCreatedContentViewing = 20,
    //    AllowProfileViewing = 21,
    //    ShowRealTimeActivity = 22,
    //    CollectVoiceDataXboxOneFull = 23,
    //    CanShareIdentity = 24,
    //    ShareContentToExternalNetworks = 25,
    //    CollectVoiceSearchData = 26,
    //    ShareClubMembership = 27,
    //    CollectVoiceGameChatData = 28,
    //    ShareActivityFeed = 29,
    //    CommunicateDuringCrossNetworkPlay = 30,
    //};
    public enum XblPrivacySetting : UInt32
    {
        Unknown = 0,
        ShareFriendList = 1,
        ShareGameHistory = 2,
        CommunicateUsingTextAndVoice = 3,
        SharePresence = 4,
        ShareProfile = 5,
        ShareVideoAndMusicStatus = 6,
        CommunicateUsingVideo = 7,
        CollectVoiceData = 8,
        ShareXboxMusicActivity = 9,
        ShareExerciseInfo = 11,
        ShareIdentity = 12,
        ShareIdentityInGame = 13,
        ShareRecordedGameSessions = 14,
        CollectLiveTvData = 15,
        CollectXboxVideoData = 16,
        ShareIdentityTransitively = 17,
        ShareVideoHistory = 18,
        ShareMusicHistory = 19,
        AllowUserCreatedContentViewing = 20,
        AllowProfileViewing = 21,
        ShowRealTimeActivity = 22,
        CollectVoiceDataXboxOneFull = 23,
        CanShareIdentity = 24,
        ShareContentToExternalNetworks = 25,
        CollectVoiceSearchData = 26,
        ShareClubMembership = 27,
        CollectVoiceGameChatData = 28,
        ShareActivityFeed = 29,
        CommunicateDuringCrossNetworkPlay = 30,
    }
}